# Generated by Django 2.2.5 on 2021-07-26 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='instant_bok',
            new_name='instant_book',
        ),
    ]
